config/routes.rb
Rails.application.routes.draw do
  resources :coach_notifications
  root 'home#index'

  # Admin Panel
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Auth
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # Password Reset
  resources :password_resets
  get 'reset-password', to: 'password_resets#new', as: 'reset_password'
  get 'check-your-email', to: 'password_resets#check', as: 'check_your_email'
  
  # User
  resources :users
  get 'update-user-info', to: 'users#edit', as: 'update_user_info'

  # App
  get 'dashboard', to: 'users#dashboard', as: 'dashboard'
  resources :invitations
  resources :techniques
  resources :likes

  # Clients
  resources :clients
  resources :completed_steps
  get 'update-client-info', to: 'clients#edit', as: 'update_client_info'
  get 'my-techniques', to: 'techniques#my', as: 'my_techniques'
  get 'recommended-techniques', to: 'techniques#recommended', as: 'recommended_techniques'
  get 'in-progress-techniques', to: 'techniques#in_progress', as: 'in_progress_techniques'
  get 'completed-techniques', to: 'techniques#completed', as: 'completed_techniques'

  # Coaches
  resources :coaches
  get 'update-coach-info', to: 'coaches#edit', as: 'update_coach_info'
  get 'all-techniques', to: 'techniques#all', as: 'all_techniques'
  resources :clients_techniques

  # All others
  # resources :steps_techniques
  # resources :notifications
  # resources :problems_techniques
  # resources :steps
  # resources :genders_techniques
  # resources :coaches_problems
  # resources :clients_problems
  # resources :problems
  # resources :genders
end

app/models/technique.rb
class Technique < ApplicationRecord
  self.primary_key = "id"

  validates :title, presence: true
  validates :description, presence: true
  as_enum :gender, both: 2, female: 1, male: 0

  validates :age_start, numericality: { only_integer: true, in: 18..99 }
  validates :age_end, numericality: { only_integer: true, in: 18..99 }

  validates :duration_start, numericality: { only_integer: true, in: 18..99 }
  validates :duration_end, numericality: { only_integer: true, in: 18..99 }

  has_many :clients_technique, dependent: :delete_all
  has_many :clients, through: :clients_technique

  has_many :likes, dependent: :delete_all
  has_many :clients, through: :likes

  has_and_belongs_to_many :problems
  has_and_belongs_to_many :steps

  scope :where_client, ->(client) { client.techniques.uniq }
end

app/controllers/techniques_controller.rb
class TechniquesController < InheritedResources::Base
  def show
    @technique = Technique.find_by_id(params[:id])

    @steps = @technique.steps
    @step = nil
    @step_count = 0
    @step_all = @steps.count

    unless current_user.client.nil?
      @steps.each do |step|
        @step = step
        @step_count += 1
        break if CompletedStep.where(client: current_user.client, step: step).empty?
      end

      @steps = nil
    end
  end

  def all
    if !params.key?(:filters) or (params[:filters][:problem_ids].count == 1 and params[:filters][:genders].count == 1)
      @techniques = Technique.all
    else
      filters = params[:filters].slice!(:problem_ids, :genders)
      @techniques = Technique.all

      if filters[:problem_ids].count > 1
        problems = filters[:problem_ids].split(',')

        problems.each do |problem|
          @techniques = @techniques.joins(:problems_techniques).where('problems_techniques.problem_id' => problem)
        end

      end

      if filters[:genders].count > 1
        genders = filters[:genders].join(',')
        
        if genders == 'male'
          @techniques = @techniques.males
        elsif genders == 'female'
          @techniques = @techniques.females
        end
      end
    end
  end

  private
  def technique_params
    params.require(:technique).permit(:title, :description, :image, :age_start, :age_end, :duration_start, :duration_end)
  end
end

app/views/techniques/_form.html.erb
<%= form_with(model: technique) do |form| %>
  <% if technique.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(technique.errors.count, "error") %> prohibited this technique from being saved:</h2>

      <ul>
        <% technique.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :age_start %>
    <%= form.number_field :age_start %>
  </div>

  <div class="field">
    <%= form.label :age_end %>
    <%= form.number_field :age_end %>
  </div>

  <div class="field">
    <%= form.label :duration_start %>
    <%= form.number_field :duration_start %>
  </div>

  <div class="field">
    <%= form.label :duration_end %>
    <%= form.number_field :duration_end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/techniques/all.html.erb
<%= render 'layouts/navigation', nav_for: 'app', user: current_user %>

<p id="alert"><%= alert %></p>
<p id="notice"><%= notice %></p>

<div class="all-techniques coaches-view">
  <div class="left-column">
    <div class="filters">
      <h3>Filters</h3>

      <%= form_with url: '/all-techniques', method: :get do |f| %>
        <div class="problem field mb-3">
          <p>Problem<br>
            <%= collection_check_boxes('filters', 'problem_ids', Problem.all, :id, :name) %>
          </p>
        </div>

        <div class="gender field mb-3">
          <p>Gender<br>
            <%= collection_check_boxes('filters', 'genders', Client.genders.hash, :first, :first) %>
          </p>
        </div>

        <div class='actions'>
          <%= f.submit 'SEARCH', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="right-column">
    <div class="techniques">
      <% @techniques.each do |technique| %>
        <%= render 'layouts/technique', technique: technique, show_details: true, for_view: "coach" %>
      <% end %>
    </div>
  </div>

</div>

<%= render 'layouts/footer' %>

app/views/techniques/completed.html.erb
<%= render 'layouts/navigation', nav_for: 'app', user: current_user %>

<p id="alert"><%= alert %></p>
<p id="notice"><%= notice %></p>

<div class="all-techniques">
  <div class="links">
    <p><%= link_to "My Techniques", my_techniques_path %></p>
    <p><%= link_to "Recommended", recommended_techniques_path %></p>
    <p><%= link_to "In progress", in_progress_techniques_path %></p>
    <p>Completed</p>
  </div>
  <hr />

  <div class="techniques-coach">
    <div class="left-column">
      <div class="techniques">
        <% techniques_completed(current_user.client).each do |technique| %>
          <%= render 'layouts/technique', technique: technique, show_continue: true, show_details: false, for_view: "client" %>
        <% end %>
      </div>
    </div>

    <div class="right-column">
      <% unless Coach.where_client(current_user.client).empty? %>
        <%= render 'layouts/coach', user: Coach.where_client(current_user.client).first.user, full_info: true %>
      <% end %>
    </div>
  </div>
</div>

<%= render 'layouts/footer' %>

app/views/techniques/in_progress.html.erb
<%= render 'layouts/navigation', nav_for: 'app', user: current_user %>

<p id="alert"><%= alert %></p>
<p id="notice"><%= notice %></p>

<div class="all-techniques">
  <div class="links">
    <p><%= link_to "My Techniques", my_techniques_path %></p>
    <p><%= link_to "Recommended", recommended_techniques_path %></p>
    <p>In progress</p>
    <p><%= link_to "Completed", completed_techniques_path %></p>
  </div>
  <hr />

  <div class="techniques-coach">
    <div class="left-column">
      <div class="techniques">
        <% techniques_in_progress(current_user.client).each do |technique| %>
          <%= render 'layouts/technique', technique: technique, show_continue: true, for_view: "client" %>
        <% end %>
      </div>
    </div>

    <div class="right-column">
      <% unless Coach.where_client(current_user.client).empty? %>
        <%= render 'layouts/coach', user: Coach.where_client(current_user.client).first.user, full_info: true %>
      <% end %>
    </div>
  </div>
</div>

<%= render 'layouts/footer' %>

app/views/techniques/my.html.erb
<%= render 'layouts/navigation', nav_for: 'app', user: current_user %>

<p id="alert"><%= alert %></p>
<p id="notice"><%= notice %></p>

<div class="all-techniques">
  <div class="links">
    <p>My Techniques</p>
    <p><%= link_to "Recommended", recommended_techniques_path %></p>
    <p><%= link_to "In progress", in_progress_techniques_path %></p>
    <p><%= link_to "Completed", completed_techniques_path %></p>
  </div>
  <hr />

  <div class="techniques-coach">
    <div class="left-column">
      <div class="techniques">
        <% Technique.where_client(current_user.client).each do |technique| %>
          <%= render 'layouts/technique', technique: technique, show_continue: true, for_view: "client" %>
        <% end %>
      </div>
    </div>

    <div class="right-column">
      <% unless Coach.where_client(current_user.client).empty? %>
        <%= render 'layouts/coach', user: Coach.where_client(current_user.client).first.user, full_info: true %>
      <% end %>
    </div>
  </div>
</div>

<%= render 'layouts/footer' %>

app/views/techniques/recommended.html.erb
<%= render 'layouts/navigation', nav_for: 'app', user: current_user %>

<p id="alert"><%= alert %></p>
<p id="notice"><%= notice %></p>

<div class="all-techniques">
  <div class="links">
    <p><%= link_to "My Techniques", my_techniques_path %></p>
    <p>Recommended</p>
    <p><%= link_to "In progress", in_progress_techniques_path %></p>
    <p><%= link_to "Completed", completed_techniques_path %></p>
  </div>
  <hr />

  <div class="techniques-coach">
    <div class="left-column">
      <div class="techniques">
        <% techniques_not_started(current_user.client).each do |technique| %>
          <%= render 'layouts/technique', technique: technique, show_continue: true, for_view: "client" %>
        <% end %>
      </div>
    </div>

    <div class="right-column">
      <% unless Coach.where_client(current_user.client).empty? %>
        <%= render 'layouts/coach', user: Coach.where_client(current_user.client).first.user, full_info: true %>
      <% end %>
    </div>
  </div>
</div>

<%= render 'layouts/footer' %>

app/views/techniques/show.html.erb
<%= render 'layouts/navigation', nav_for: 'app', user: current_user %>

<p id="alert"><%= alert %></p>
<p id="notice"><%= notice %></p>

<% if @steps.nil? %>
  <div class="technique-view">
    <div class="step">
      <h1><%= @step.title %></h1>

      <p><%= @step.description %></p>

      <% unless @step.image.nil? %>
        <%= image_tag @step.image, :alt => @step.title %>
      <% end %>

      <% unless @step.video.nil? %>
        <%= video_tag @step.video, :controls => true %>
      <% end %>

      <% unless @step.audio.nil? %>
        <%= audio_tag @step.audio, :controls => true %>
      <% end %>

      <div class="buttons">
        <% if @step_count == 1 %>
          <div class="button">
            <p>Go back</p>
          </div>
        <% else %>
          <div class="button">
            <p><%= link_to "Go Back", edit_completed_step_path(@step, step_id: (@step.id - 1), technique_id: @technique.id, delete: true) %></p>
          </div>
        <% end %>

        <div class="button text-center">
          <p>Step <%= @step_count %> of <%= @step_all %></p>
        </div>

        <% if @step_count < @step_all %>
          <div class="button text-right">
            <p><%= link_to "Next Step", new_completed_step_path(@step, step_id: @step.id, technique_id: @technique.id, last_step: false) %></p>
          </div>
        <% else %>
          <div class="button text-right">
            <p><%= link_to "Finish", new_completed_step_path(@step, step_id: @step.id, technique_id: @technique.id, last_step: true) %></p>
          </div>
        <% end %>
      </div>
    </div>

    <div class="technique">
      <%= render 'layouts/technique', technique: @technique, show_continue: false, for_view: "client" %>
    </div>
  </div>

<% else %>
  <div class="technique-view">
    <div class="step">
      <% step_count = 0 %>
      <% @steps.each do |step| %>
        <% step_count += 1%>

        <h1><%= step_count %>/<%= @step_all %> <%= step.title %></h1>

        <p><%= step.description %></p>

        <% unless step.image.nil? %>
          <%= image_tag step.image, :alt => step.title %>
        <% end %>

        <% unless step.video.nil? %>
          <%= video_tag step.video, :controls => true %>
        <% end %>

        <% unless step.audio.nil? %>
          <%= audio_tag step.audio, :controls => true %>
        <% end %>

        <hr class="mb-5">
      <% end %>
    </div>

    <div class="technique">
      <%= render 'layouts/technique', technique: @technique, show_details: false, for_view: "coach" %>
      
      <div class="link">
        <p><%= link_to 'RECOMMEND TO CLIENTS', new_clients_technique_path(technique_id: @technique.id), class: 'btn btn-primary' %></p>
      </div>
    </div>
  </div>

<% end %>

<%= render 'layouts/footer' %>