config/routes.rb
Rails.application.routes.draw do
  resources :coach_notifications
  root 'home#index'

  # Admin Panel
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Auth
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # Password Reset
  resources :password_resets
  get 'reset-password', to: 'password_resets#new', as: 'reset_password'
  get 'check-your-email', to: 'password_resets#check', as: 'check_your_email'
  
  # User
  resources :users
  get 'update-user-info', to: 'users#edit', as: 'update_user_info'

  # App
  get 'dashboard', to: 'users#dashboard', as: 'dashboard'
  resources :invitations
  resources :techniques
  resources :likes

  # Clients
  resources :clients
  resources :completed_steps
  get 'update-client-info', to: 'clients#edit', as: 'update_client_info'
  get 'my-techniques', to: 'techniques#my', as: 'my_techniques'
  get 'recommended-techniques', to: 'techniques#recommended', as: 'recommended_techniques'
  get 'in-progress-techniques', to: 'techniques#in_progress', as: 'in_progress_techniques'
  get 'completed-techniques', to: 'techniques#completed', as: 'completed_techniques'

  # Coaches
  resources :coaches
  get 'update-coach-info', to: 'coaches#edit', as: 'update_coach_info'
  get 'all-techniques', to: 'techniques#all', as: 'all_techniques'
  resources :clients_techniques

  # All others
  # resources :steps_techniques
  # resources :notifications
  # resources :problems_techniques
  # resources :steps
  # resources :genders_techniques
  # resources :coaches_problems
  # resources :clients_problems
  # resources :problems
  # resources :genders
end

app/models/user.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors.add attribute, (options[:message] || "is not an email")
    end
  end
end

class User < ApplicationRecord
  self.primary_key = "id"
  
  validates :name, presence: true
  validates :email, email: true, uniqueness: true
  
  has_secure_password

  has_one :client, dependent: :delete
  has_one :coach, dependent: :delete

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.forgot_password(self).deliver
  end
  
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def profile
    self.client.nil? ? self.coach : self.client
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  def index
    @users = User.all
    redirect_to dashboard_path
  end

  def show
    redirect_to dashboard_path
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to login_path, notice: "You can now login with your credentials" }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        text = "You have updated your credentials"
        Notification.create!(client: @user.client, text: text) unless @user.client.nil?
        CoachNotification.create!(coach: @user.coach, text: text) unless @user.coach.nil?

        format.html { redirect_to dashboard_path, notice: text }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed" }
      format.json { head :no_content }
    end
  end

  def dashboard
    redirect_to new_client_path and return if current_user.profile.nil? 
    unless current_user.client.nil?
      render :action => 'dashboard_client', :view => 'users'
    else
      render :action => 'dashboard_coach', :view => 'users'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find_by_id(params[:id])
      @user = current_user if @user.nil?
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :is_verified, :send_email_notifications)
    end
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :is_verified %>
    <%= form.check_box :is_verified %>
  </div>

  <div class="field">
    <%= form.label :send_email_notifications %>
    <%= form.check_box :send_email_notifications %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/dashboard.html.erb
<h1>Dashboard</h1>

<p><%= @user.name %></p>
<p><%= @user.email %></p>
<p><%= @user.profile.age %> years | <%= @user.profile.gender.name %></p>

<p>Total progress: <strong><%= @user.client.techniques_completed_count %></strong> techniques completed</p>
<p>Current progress: <strong><%= @user.client.techniques_in_progress_count %></strong> techniques in process</p>
<p>Total time: <strong><%= @user.client.hours_completed %></strong> hours for techniques</p>
<p>Current time: <strong><%= @user.client.hours_in_progress %></strong> hours for techniques</p>

<p>Problems:
  <% @user.profile.problems.each do |problem| %>
    <%= problem.name %>
  <% end %>
</p>

<p>Current coach: <%= @user.client.coach_user.name %></p>

<p>Notifications:</p>
<p>
  <% @user.profile.notifications.each do |notification| %>
    <span><%= notification.text %><br></span>
  <% end %>
</p>

<p>Techniques:</p>
<p>
  <% @user.profile.techniques.each do |technique| %>
    <span>Title: <strong><%= technique.title %></strong><br></span>
    <span>Description: <strong><%= technique.description %></strong><br></span>
    <span>Age: <strong><%= technique.age_start %>-<%= technique.age_end %> years</strong><br></span>
    <span><strong><%= @user.client.completed_steps_count(technique) %>/<%= technique.steps.count %> steps passed</strong><br></span>

    <span>Problems: <strong>
      <% technique.problems.each do |problem| %>
        <span><%= problem.name %></span>
      <% end %>
    </strong><br></span>

    <span>Gender: <strong>
      <% technique.genders.each do |gender| %>
        <span><%= gender.name %></span>
      <% end %>
    </strong><br></span>

    <span>Steps: <strong><%= technique.steps.count %></strong><br></span>

    <span>Duration: <strong>
      <% if technique.duration_start == technique.duration_end %>
        <%= technique.duration_start %>
      <% else %>
        <%= technique.duration_start %>-<%= technique.duration_end %>
      <% end %>
    hours</strong><br></span>


    <span>Participants: <strong><%= technique.clients.count %></strong><br></span>
    <span>Likes: <strong><%= technique.likes %></strong><br></span>
    <span>Dislikes: <strong><%= technique.dislikes %></strong><br></span>

    <span>
      <% if @user.client.completed_steps_count(technique) == 0 %>
        GET STARTED
      <% elsif @user.client.completed_steps_count(technique) < technique.steps.count %>
        CONTINUE
      <% else %>
        RESTART
      <% end %>
    <br></span>
    <br>
  <% end %>
</p>

app/views/users/dashboard_client.html.erb
<%= render 'layouts/navigation', nav_for: 'app', user: current_user %>

<p id="alert"><%= alert %></p>
<p id="notice"><%= notice %></p>

<div class="dashboard">

  <div class="left-column">

    <div class="analytics">
      <div class="analytic">
        <p class="title">Total progress</p>

        <div class="number-description">
          <div class="number">
            <p><strong><%= current_user.client.total_progress %></strong></p>
          </div>

          <div class="description">
            <p class="text-muted font-size-small">techniques<br>completed</p>
          </div>
        </div>
      </div>
      
      <div class="analytic">
        <p class="title">Current progress</p>

        <div class="number-description">
          <div class="number">
            <p><strong><%= current_user.client.current_progress %></strong></p>
          </div>

          <div class="description">
            <p class="text-muted font-size-small">techniques in<br>process</p>
          </div>
        </div>
      </div>
      
      <div class="analytic">
        <p class="title">Total time</p>

        <div class="number-description">
          <div class="number">
            <p><strong><%= current_user.client.total_time.round(1) %></strong></p>
          </div>

          <div class="description">
            <p class="text-muted font-size-small">hours for<br>techniques</p>
          </div>
        </div>
      </div>
      
      <div class="analytic">
        <p class="title">Current time</p>

        <div class="number-description">
          <div class="number">
            <p><strong><%= current_user.client.current_time.round(1) %></strong></p>
          </div>

          <div class="description">
            <p class="text-muted font-size-small">hours for<br>techniques</p>
          </div>
        </div>
      </div>
    </div>

    <h3 class="mt-3">My Techniques</h3>
    
    <div class="techniques">
      <% Technique.where_client(current_user.client).each do |technique| %>
        <%= render 'layouts/technique', technique: technique, show_continue: true, for_view: "client" %>
      <% end %>
    </div>

  </div>

  <div class="right-column">

    <div class="client-card">
      <div class="image-info">
        <div class="image">
          <%= image_tag(profile_image(current_user), size: "50x50", alt: current_user.name) %>
        </div>

        <div class="info">
          <p>
            <strong><%= current_user.name %></strong>
            <%= link_to "[Edit]", update_client_info_path %>
          </p>
          
          <p><%= current_user.email %></p>
          <p><%= current_user.profile.age %> years | <%= current_user.profile.gender %></p>
        </div>
      </div>

      <p>Problems</p>
      <div class="problems">
        <% current_user.profile.problems.each do |problem| %>
          <div class="problem"><%= problem.name %></div>
        <% end %>
      </div>
    </div>

    <div class="coach-card">
      <% if Coach.where_client(current_user.client).empty? %>
        <% if Coach.unconfirmed(current_user.client).empty? %>
          <p><%= link_to "You don't have a coach yet", coaches_path %></p>
        <% else %>
          <p>Waiting for confirmation</p>
          <p><strong><%= Coach.unconfirmed(current_user.client).first.name %></strong></p>
          <p><%= link_to 'CANCEL', current_user.client.invitations.where(status: 0).last %></p>
        <% end %>
      <% else %>
        <p>Current coach</p>

        <div class="image-info">
          <div class="image">
            <%= image_tag(profile_image(Coach.where_client(current_user.client).first.user), size: "50x50", alt: Coach.where_client(current_user.client).first.name) %>
          </div>

          <div class="info">
            <p><strong><%= Coach.where_client(current_user.client).first.name %></strong></p>
            <p><%= link_to 'End Cooperation', current_user.client.invitations.where(status: 1).last %></p>
          </div>
        </div>
      <% end %>
    </div>

    <div class="notifications">
      <h3>Notifications</h3>

      <% current_user.profile.notifications.last(10).reverse.each do |notification| %>
        <div class="client-card">
          <div class="image-info">
            <div class="image">
              <%= image_tag(profile_image(current_user), size: "50x50", alt: current_user.name) %>
            </div>

            <div class="info">
              <p><%= notification.text %><br></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>

  </div>

</div>

<%= render 'layouts/footer' %>

app/views/users/dashboard_coach.html.erb
<%= render 'layouts/navigation', nav_for: 'app', user: current_user %>

<p id="alert"><%= alert %></p>
<p id="notice"><%= notice %></p>

<div class="dashboard">

  <div class="left-column">

    <div class="analytics text-center">
      <div class="analytic">
        <p class="title">Total number of<br>clients</p>

        <div class="number">
          <p><strong><%= current_user.coach.total_clients_count %></strong></p>
        </div>
      </div>

      <div class="analytic">
        <p class="title">Current number of<br>users</p>

        <div class="number">
          <p><strong><%= current_user.coach.active_clients_count %></strong></p>
        </div>
      </div>

      <div class="analytic">
        <p class="title">Total number of<br>techniques used</p>

        <div class="number">
          <p><strong><%= current_user.coach.techniques_count %></strong></p>
        </div>
      </div>

      <div class="analytic">
        <p class="title">Total number of<br>likes</p>

        <div class="number">
          <p><strong><%= current_user.coach.likes_count %></strong></p>
        </div>
      </div>
    </div>

    <h3 class="mt-3">My clients</h3>

    <div class="clients">
      <% Client.where_coach(current_user.coach).each do |client| %>
        <%= render 'layouts/client', user: client.user, invitation: nil %>
      <% end %>
    </div>

    <h3 class="mt-3">Techniques</h3>

    <div class="techniques">
      <% Client.where_coach(current_user.coach).each do |client| %>
        <% techniques_in_progress(client).each do |technique| %>
          <%= render 'layouts/technique', technique: technique, show_details: true, for_view: "coach" %>
        <% end %>
      <% end %>
    </div>

  </div>

  <div class="right-column">
    <div class="client-card">
      <div class="image-info">
        <div class="image">
          <%= image_tag(profile_image(current_user), size: "50x50", alt: current_user.name) %>
        </div>

        <div class="info">
          <p>
            <strong><%= current_user.name %></strong>
            <%= link_to "[Edit]", update_coach_info_path %>
          </p>
          
          <p><%= current_user.email %></p>
          <p><%= current_user.profile.age %> years | <%= current_user.profile.gender %></p>
        </div>
      </div>

      <p>Areas of Expertise</p>
      <div class="problems">
        <% current_user.profile.problems.each do |problem| %>
          <div class="problem"><%= problem.name %></div>
        <% end %>
      </div>
    </div>

    <div class="notifications">
      <h3>Notifications</h3>

      <% current_user.profile.coach_notifications.last(10).reverse.each do |notification| %>
        <div class="client-card">
          <div class="image-info">
            <div class="image">
              <%= image_tag(profile_image(current_user), size: "50x50", alt: current_user.name) %>
            </div>

            <div class="info">
              <p><%= notification.text %><br></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>

  </div>

</div>

<%= render 'layouts/footer' %>

app/views/users/edit.html.erb
<%= render 'layouts/navigation', nav_for: 'app', user: current_user %>

<div class="login">
  <p id="alert"><%= alert %></p>
  <p id="notice"><%= notice %></p>

  <h1 class="text-center">Update credentials</h1>

  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class='error_messages'>
        <% for message in @user.errors.full_messages %>
          <p class='color-red'><%= message %></p>
        <% end %>
      </div>
    <% end %>

    <div class='field mb-3'>
      <%= f.label :name, class: 'form-label' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class='field mb-3'>
      <%= f.label :email, class: 'form-label' %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>

    <div class='field mb-3'>
      <%= f.label :password, class: 'form-label' %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>

    <div class='field mb-3'>
      <%= f.label :password_confirmation, class: 'form-label' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>

    <div class='actions mb-3'>
      <%= f.submit 'SAVE CHANGES', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

<%= render 'layouts/footer' %>

app/views/users/new.html.erb
<%= render 'layouts/navigation', nav_for: 'login' %>

<div class="login">
  <p id="alert"><%= alert %></p>
  <p id="notice"><%= notice %></p>

  <h1 class="text-center">Create account</h1>

  <p class="description text-center">Already have an account? &nbsp; <strong><%= link_to "Sign in", login_path %></strong></p>

  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class='error_messages'>
        <% for message in @user.errors.full_messages %>
          <p class='color-red'><%= message %></p>
        <% end %>
      </div>
    <% end %>

    <div class='field mb-3'>
      <%= f.label :name, class: 'form-label' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class='field mb-3'>
      <%= f.label :email, class: 'form-label' %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>

    <div class='field mb-3'>
      <%= f.label :password, class: 'form-label' %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>

    <div class='field mb-3'>
      <%= f.label :password_confirmation, class: 'form-label' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>

    <div class='actions mb-3'>
      <%= f.submit 'SIGN UP', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

<%= render 'layouts/footer' %>