config/routes.rb
Rails.application.routes.draw do
  resources :coach_notifications
  root 'home#index'

  # Admin Panel
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Auth
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # Password Reset
  resources :password_resets
  get 'reset-password', to: 'password_resets#new', as: 'reset_password'
  get 'check-your-email', to: 'password_resets#check', as: 'check_your_email'
  
  # User
  resources :users
  get 'update-user-info', to: 'users#edit', as: 'update_user_info'

  # App
  get 'dashboard', to: 'users#dashboard', as: 'dashboard'
  resources :invitations
  resources :techniques
  resources :likes

  # Clients
  resources :clients
  resources :completed_steps
  get 'update-client-info', to: 'clients#edit', as: 'update_client_info'
  get 'my-techniques', to: 'techniques#my', as: 'my_techniques'
  get 'recommended-techniques', to: 'techniques#recommended', as: 'recommended_techniques'
  get 'in-progress-techniques', to: 'techniques#in_progress', as: 'in_progress_techniques'
  get 'completed-techniques', to: 'techniques#completed', as: 'completed_techniques'

  # Coaches
  resources :coaches
  get 'update-coach-info', to: 'coaches#edit', as: 'update_coach_info'
  get 'all-techniques', to: 'techniques#all', as: 'all_techniques'
  resources :clients_techniques

  # All others
  # resources :steps_techniques
  # resources :notifications
  # resources :problems_techniques
  # resources :steps
  # resources :genders_techniques
  # resources :coaches_problems
  # resources :clients_problems
  # resources :problems
  # resources :genders
end

app/models/client.rb
class Client < ApplicationRecord
  self.primary_key = "id"

  validates :age, numericality: { only_integer: true, in: 18..99 }
  validates :problems, presence: true
  as_enum :gender, female: 1, male: 0

  has_one_attached :image
  
  has_many :invitations, dependent: :delete_all
  has_many :coaches, through: :invitations
  
  has_many :completed_steps, dependent: :delete_all
  has_many :steps, through: :completed_steps

  has_many :likes, dependent: :delete_all
  has_many :techniques, through: :likes

  has_many :notifications, dependent: :delete_all
  
  belongs_to :user

  has_and_belongs_to_many :problems
  has_and_belongs_to_many :techniques

  def name
    self.user.name
  end

  scope :where_coach, ->(coach) { find_by_sql(["SELECT clients.id, clients.user_id, clients.age, clients.gender_cd, clients.current_progress FROM (SELECT * FROM invitations WHERE status=1 AND coach_id=?) AS a INNER JOIN clients ON a.client_id = clients.id", coach.id]) }
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]
  
  def index
    @clients = Client.where_coach(current_user.coach)
  end

  def show
  end

  def new
    @client = Client.new
  end

  def edit
  end

  def create
    @client = Client.new(client_params)
    @client.user = current_user
  
    params[:client][:problem_ids].each do |pr|
      problem = Problem.find_by_id(pr)
      @client.problems << problem unless problem.nil?
    end

    respond_to do |format|
      if @client.save
        text = "#{@client.name}, you have completed the registration"

        Notification.create!(client: @client, text: text)
        format.html { redirect_to dashboard_path, notice: text }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @client.update(client_params)
        @client.problems.destroy_all
        params[:client][:problem_ids].each do |pr|
          problem = Problem.find_by_id(pr)
          @client.problems << problem unless problem.nil?
        end
        
        text = 'You have updated your personal information'

        Notification.create!(client: @client, text: text)
        format.html { redirect_to dashboard_path, notice: text }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to root_url, notice: "Client was successfully destroyed" }
      format.json { head :no_content }
    end
  end

  private
    def set_client
      @client = Client.find_by_id(params[:id])
      @client = current_user.client if @client.nil?
    end

    def client_params
      params.require(:client).permit(:image, :age, :bio, :user_id, :gender, :problem_ids)
    end
end

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_field :bio %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :gender_id %>
    <%= form.text_field :gender_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<%= render 'layouts/navigation', nav_for: 'app', user: current_user %>

<div class="login">
  <p id="alert"><%= alert %></p>
  <p id="notice"><%= notice %></p>

  <h1 class="text-center">Personal information</h1>

  <p class="text-center"><%= link_to "Update your credentials", update_user_info_path %></p>

  <%= form_for @client do |f| %>
    <% if @client.errors.any? %>
      <div class='error_messages'>
        <% for message in @client.errors.full_messages %>
          <p class='color-red'><%= message %></p>
        <% end %>
      </div>
    <% end %>

    <div class='field mb-3'>
      <%= f.label :image, class: 'form-label' %>
      <%= f.file_field :image, class: 'form-control' %>
      <p class="text-muted font-size-small">Image format should be png, jpg no more than 5 Mb</p>
    </div>

    <div class='field mb-3'>
      <%= f.label :age, class: 'form-label' %>
      <%= f.number_field :age, in: 18..99, class: 'form-control' %>
    </div>

    <div class='field mb-3'>
      <%= f.label :gender_id, class: 'form-label' %>
      <%= collection_radio_buttons('client', 'gender', Client.genders.hash, :first, :first) %>
    </div>

    <div class='field mb-3'>
      <%= f.label :problem_ids, class: 'form-label' %>
      <%= collection_check_boxes('client', 'problem_ids', Problem.all, :id, :name) %>
    </div>

    <div class='field mb-3'>
      <%= f.label :bio, class: 'form-label' %>
      <%= f.text_area :bio, class: 'form-control' %>
      <p class="text-muted font-size-small text-center">This information will help the coach to better understand your problem and assess whether he is able to help you</p>
    </div>

    <div class='actions mb-3'>
      <%= f.submit 'SAVE CHANGES', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

<%= render 'layouts/footer' %>

app/views/clients/index.html.erb
<%= render 'layouts/navigation', nav_for: 'app', user: current_user %>

<p id="alert"><%= alert %></p>
<p id="notice"><%= notice %></p>

<div class="my-clients">
  <div class="links">
    <p>My Clients</p>
    <p><%= link_to "Waiting for confirmation (#{current_user.coach.invitations_count})", invitations_path %></p>
  </div>
  <hr />

  <div class="clients">
    <% @clients.each do |client| %>
      <%= render 'layouts/client', user: client.user, invitation: nil %>
    <% end %>
  </div>
</div>

<%= render 'layouts/footer' %>

app/views/clients/new.html.erb
<%= render 'layouts/navigation', nav_for: 'login' %>

<div class="login">
  <p id="alert"><%= alert %></p>
  <p id="notice"><%= notice %></p>

  <h1 class="text-center">Hello, <%= current_user.name %></h1>

  <p class="text-center"><strong>CLIENT &nbsp; <%= link_to "COACH", new_coach_path %></strong></p>

  <p class="text-center">You are registering as a Client in our system. Please, share some personal information about you so that we can personalize your onboarding experience</p>

  <%= form_for @client do |f| %>
    <% if @client.errors.any? %>
      <div class='error_messages'>
        <% for message in @client.errors.full_messages %>
          <p class='color-red'><%= message %></p>
        <% end %>
      </div>
    <% end %>

    <div class='field mb-3'>
      <%= f.label :image, class: 'form-label' %>
      <%= f.file_field :image, class: 'form-control' %>
      <p class="text-muted font-size-small">Image format should be png, jpg no more than 5 Mb</p>
    </div>

    <div class='field mb-3'>
      <%= f.label :age, class: 'form-label' %>
      <%= f.number_field :age, in: 18..99, class: 'form-control' %>
    </div>

    <div class='field mb-3'>
      <%= f.label :gender, class: 'form-label' %>
      <%= collection_radio_buttons('client', 'gender', Client.genders.hash, :first, :first) %>
    </div>

    <div class='field mb-3'>
      <%= f.label :problem_ids, class: 'form-label' %>
      <%= collection_check_boxes('client', 'problem_ids', Problem.all, :id, :name) %>
    </div>

    <div class='actions'>
      <%= f.submit 'SAVE', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

<%= render 'layouts/footer' %>

app/views/clients/show.html.erb
<%= render 'layouts/navigation', nav_for: 'app', user: current_user %>

<p id="alert"><%= alert %></p>
<p id="notice"><%= notice %></p>

<div class="dashboard">

  <div class="left-column">
    <div class="analytics">
      <div class="analytic">
        <p class="title">Total progress</p>

        <div class="number-description">
          <div class="number">
            <p><strong><%= @client.total_progress %></strong></p>
          </div>

          <div class="description">
            <p class="text-muted font-size-small">techniques<br>completed</p>
          </div>
        </div>
      </div>
      
      <div class="analytic">
        <p class="title">Current progress</p>

        <div class="number-description">
          <div class="number">
            <p><strong><%= @client.current_progress %></strong></p>
          </div>

          <div class="description">
            <p class="text-muted font-size-small">techniques in<br>process</p>
          </div>
        </div>
      </div>
      
      <div class="analytic">
        <p class="title">Total time</p>

        <div class="number-description">
          <div class="number">
            <p><strong><%= @client.total_time.round(1) %></strong></p>
          </div>

          <div class="description">
            <p class="text-muted font-size-small">hours for<br>techniques</p>
          </div>
        </div>
      </div>
      
      <div class="analytic">
        <p class="title">Current time</p>

        <div class="number-description">
          <div class="number">
            <p><strong><%= @client.current_time.round(1) %></strong></p>
          </div>

          <div class="description">
            <p class="text-muted font-size-small">hours for<br>techniques</p>
          </div>
        </div>
      </div>
    </div>

    <h3 class="mt-3">Techniques</h3>
    
    <div class="techniques">
      <% Technique.where_client(@client).each do |technique| %>
        <%= render 'layouts/technique', technique: technique, show_continue: false, for_view: "client" %>
      <% end %>
    </div>

  </div>

  <div class="right-column">

    <div class="client-card">
      <div class="image-info">
        <div class="image">
          <%= image_tag(profile_image(@client.user), size: "50x50", alt: @client.name) %>
        </div>

        <div class="info">
          <p>
            <strong><%= @client.name %></strong>
          </p>
          
          <p><%= @client.user.email %></p>
          <p><%= @client.age %> years | <%= @client.gender %></p>
        </div>
      </div>

      <p>Problems</p>
      <div class="problems">
        <% @client.problems.each do |problem| %>
          <div class="problem"><%= problem.name %></div>
        <% end %>
      </div>
    </div>

  </div>

</div>

<%= render 'layouts/footer' %>