config/routes.rb
Rails.application.routes.draw do
  resources :coach_notifications
  root 'home#index'

  # Admin Panel
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Auth
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # Password Reset
  resources :password_resets
  get 'reset-password', to: 'password_resets#new', as: 'reset_password'
  get 'check-your-email', to: 'password_resets#check', as: 'check_your_email'
  
  # User
  resources :users
  get 'update-user-info', to: 'users#edit', as: 'update_user_info'

  # App
  get 'dashboard', to: 'users#dashboard', as: 'dashboard'
  resources :invitations
  resources :techniques
  resources :likes

  # Clients
  resources :clients
  resources :completed_steps
  get 'update-client-info', to: 'clients#edit', as: 'update_client_info'
  get 'my-techniques', to: 'techniques#my', as: 'my_techniques'
  get 'recommended-techniques', to: 'techniques#recommended', as: 'recommended_techniques'
  get 'in-progress-techniques', to: 'techniques#in_progress', as: 'in_progress_techniques'
  get 'completed-techniques', to: 'techniques#completed', as: 'completed_techniques'

  # Coaches
  resources :coaches
  get 'update-coach-info', to: 'coaches#edit', as: 'update_coach_info'
  get 'all-techniques', to: 'techniques#all', as: 'all_techniques'
  resources :clients_techniques

  # All others
  # resources :steps_techniques
  # resources :notifications
  # resources :problems_techniques
  # resources :steps
  # resources :genders_techniques
  # resources :coaches_problems
  # resources :clients_problems
  # resources :problems
  # resources :genders
end

app/views/layouts/_client.html.erb
<div class="client-card">
  <div class="image-info">
    <div class="image">
      <%= image_tag(profile_image(user), size: "50x50", alt: user.name) %>
    </div>

    <div class="info">
      <p>
        <strong><%= user.name %> <%= user.is_verified %></strong>
      </p>

      <% if invitation.nil? %>
        <p>Current Client</p>
        <p><%= user.profile.age %> years | <%= user.profile.gender %></p>
      <% else %>
        <p>Client</p>
        <p><%= user.profile.age %> years | <%= user.profile.gender %></p>
        <p><%= user.profile.bio %></p>
      <% end %>
    </div>
  </div>

  <p class="mb-0">Problems</p>
  <div class="problems">
    <% user.profile.problems.each do |problem| %>
      <div class="problem"><%= problem.name %></div>
  <% end %>
  </div>

  <% if invitation.nil? %>
    <p>Techniques in process</p>
    <% if user.profile.current_progress == 0 %>
      <p>All techniques completed</p>
    <% else %>
      <% techniques_in_progress(user.profile).each do |technique| %>
        <p><strong><%= technique.title %></strong></p>
      <% end %>
    <% end %>

    <div class="link">
      <p><%= link_to 'SEE DETAILS', client_path(user.client) %></p>
    </div>
  
  <% else %>
    <p class="mb-0">Problems</p>
    <div class="problems">
      <% user.profile.problems.each do |problem| %>
        <div class="problem"><%= problem.name %></div>
    <% end %>
    </div>

    <div class="links">
      <p><%= link_to 'REFUSE', edit_invitation_path(invitation, client_id: user.client.id, is_confirmed: false) %></p>

      <p><%= link_to 'CONFIRM', edit_invitation_path(invitation, client_id: user.client.id, is_confirmed: true) %></p>
    </div>
  <% end %>
</div>

app/views/layouts/_coach.html.erb
<div class="coach-card">
  <div class="image-info">
    <div class="image">
      <%= image_tag(profile_image(user), size: "50x50", alt: user.name) %>
    </div>

    <div class="info">
      <p>
        <strong><%= user.name %> <%= user.is_verified %></strong>
      </p>

      <% if full_info %>
        <p><%= user.coach.bio %></p>
        <p><%= user.profile.age %> years | <%= user.profile.gender %> | <%= user.coach.active_clients_count %> clients</p>
      <% else %>
        <p>Coach</p>
        <p><%= user.coach.bio %></p>
        <p><%= user.profile.age %> years | <%= user.profile.gender %> | <%= user.coach.active_clients_count %> clients</p>
      <% end %>
    </div>
  </div>

  <p class="mb-0">Areas of Expertise</p>
  <div class="problems">
    <% user.profile.problems.each do |problem| %>
      <div class="problem"><%= problem.name %></div>
  <% end %>
  </div>

  <% if full_info %>
    <p class="mt-3">Education: <%= user.coach.education %></p>
    <p>Work: Experience <%= user.coach.work %></p>
    <p>Licenses and Certificates: <%= user.coach.licenses %></p>

    <% if user.coach.links.include?("://") %>
      <p>Link: <%= link_to user.coach.links.split("://")[1].split("/")[0], user.coach.links %></p>
    <% else %>
      <p>Link: <%= user.coach.links %></p>
    <% end %>

    <div class="link">
      <% if current_user.nil? %>
        <p><%= link_to 'SEND AN INVITATION', login_path %></p>
      <% elsif Coach.where_client(current_user.client).empty? %>
        <p><%= link_to 'SEND AN INVITATION', new_invitation_path(coach_id: user.coach.id) %></p>
      <% elsif Coach.where_client(current_user.client).first.id == user.coach.id %>
        <p><%= link_to 'END COOPERATION', user.coach.invitations.where(client: current_user.client, status: 1).last %></p>
      <% else %>
        <p>You cannot invite a coach. First, complete the cooperation with your current coach.</p>
      <% end %>
    </div>
  
  <% elsif !current_user.nil? %>
    <div class="link">
      <p><%= link_to 'SEE DETAILS', coach_path(user.coach) %></p>
    </div>
  
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<%# <footer class="page-footer pt-4">
    <div class="container">
        <div class="row">
            <div class="col">
                <p>&copy; 2022 All rights reserved</p>
            </div>

            <div class="col right">
                <p>
                    <a href="/">Terms</a> &emsp;
                    <a href="/">Privacy</a> &emsp;
                    <a href="/">Security</a> &emsp;
                </p>
            </div>
        </div>
    </div>
</footer> %>

app/views/layouts/_navigation.html.erb
<header class="p-3 navigation">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start nav p-2">

      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-decoration-none logo">Wellnest</a>
      
      <% if nav_for == 'home' %>
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="#how-does-it-work" class="nav-link px-2">How does it work?</a></li>
          <li><a href="#techniques" class="nav-link px-2">Techniques</a></li>
          <li><a href="#coaches" class="nav-link px-2">Coaches</a></li>
        </ul>

        <div class="text-end">
          <%= link_to "SIGN IN", "login", class: "btn btn-primary me-2" %>
        </div>

      <% elsif nav_for == 'login' %>
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="/login" class="nav-link px-2">Sign in</a></li>
          <li><a href="/signup" class="nav-link px-2">Sign up</a></li>
          <li><a href="/reset-password" class="nav-link px-2">Reset Password</a></li>
        </ul>

      <% elsif nav_for == 'app' %>
        <% unless user.nil? %>
          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><a href="/dashboard" class="nav-link px-2">Dashboard</a></li>

            <% if user.coach.nil? %>
              <li><a href="/my-techniques" class="nav-link px-2">My Techniques</a></li>
              <li><a href="/coaches" class="nav-link px-2">Coaches</a></li>
            <% else %>
              <li><a href="/clients" class="nav-link px-2">My Clients
                <% if current_user.coach.invitations_count > 0 %>
                  (<%= current_user.coach.invitations_count %>)</a></li>
                <% end %>
              </a></li>
              
              <li><a href="/all-techniques" class="nav-link px-2">All Techniques</a></li>
            <% end %>
          </ul>

          <div class="text-end">
            <%= image_tag(profile_image(user), size: "30x30", alt: user.name) %> &nbsp;
            <a href="/logout" class="btn btn-primary me-2">LOG OUT</a>
          </div>
        <% end %>

      <% end %>
    </div>
  </div>
</header>

app/views/layouts/_technique.html.erb
<div class="technique">
  <% if for_view == 'client' %>
    <div class="tag badge rounded-pill bg-secondary"><%= completed_steps_in_technique(current_user.client, technique) %>/<%= technique.steps.count %> steps passed</div>
  <% end %>
  
  <div class="symptoms d-flex">
    <% technique.problems.each do |problem| %>
      <div class="symptom"><%= problem.name %></div>
    <% end %>
  </div>

  <%= image_tag(cover_image(technique), :alt => technique.title, :class => "card-img-top") %>

  <div class="card-body">
    <h5 class="card-title"><%= technique.title %></h5>
    <p class="card-text">
      <small>
        <span class="text-muted"><%= technique.description %></span><br />
        <br />

        <span class="text-muted">Age:</span>
        <% if technique.age_start == technique.age_end %>
          <%= technique.age_start %>
        <% else %>
          <%= technique.age_start %>-<%= technique.age_end %>
        <% end %>
        <span>years</span><br />

        <span class="text-muted">Gender:</span>
        <% if technique.gender.eql?(:both) %>
          male, female
        <% else %>
          <%= technique.gender %>
        <% end %>
        </span><br />

        <br />
        <span class="text-muted">Steps:</span> <%= technique.steps.count %><br />

        <span class="text-muted">Duration:</span>
        <% if technique.duration_start == technique.duration_end %>
          <%= technique.duration_start %>
        <% else %>
          <%= technique.duration_start %>-<%= technique.duration_end %>
        <% end %>
        <span>hours</span><br />

        <span class="text-muted">
          Participants: <%= technique.clients.count %> &emsp;
          Likes: <%= technique.likes.where(is_like: true).count %> &emsp;
          Dislikes: <%= technique.likes.where(is_like: false).count %>
        </span>
      </small>
    </p>

    <div class="link">
      <% if for_view == 'coach' %>
        <% if show_details == true %>
          <p><%= link_to "DETAILS", technique_path(technique) %><p>
        <% end %>

      <% elsif for_view == 'client' %>
        <% if show_continue == true %>
          <p>
            <% if completed_steps_in_technique(current_user.client, technique) == 0 %>
              <%= link_to "GET STARTED", technique_path(technique) %>
            <% elsif completed_steps_in_technique(current_user.client, technique) < technique.steps.count %>
              <%= link_to "CONTINUE", technique_path(technique) %>
            <% else %>
              <%= link_to "RESTART", technique_path(technique) %>
            <% end %>
          </p>
        <% end %>
      
      <% end %>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" sizes="180x180" href="/icons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/icons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/icons/favicon-16x16.png">
    <link rel="manifest" href="/icons/site.webmanifest">
    <link rel="mask-icon" href="/icons/safari-pinned-tab.svg" color="#ea5a47">
    <link rel="shortcut icon" href="/icons/favicon.ico">
    <meta name="apple-mobile-web-app-title" content="Mental Health Coaching">
    <meta name="application-name" content="Mental Health Coaching">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="msapplication-config" content="/icons/browserconfig.xml">
    <meta name="theme-color" content="#495057">

    <title>Mental Health Coaching</title>
    <meta name="description" content="Platform where coaches help users to deal with anxiety and depression">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    
    <%= yield %>
  </body>
</html>